# deploy on vercel and cloud server
name: deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: install dependeces
        run: |
          npm i yarn
          npm i vercel
          yarn install

      - name: build site
        run: |
          yarn build
          mv ./build ./docs/yiri-mirai

      - name: vercel deploy
        run: |
          vercel link "$PWD/docs/yiri-mirai" --confirm --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy "$PWD/docs/yiri-mirai" --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: cloud server deploy
        run: |
          echo ${{ secrets.SCP_PEM_B64 }} > V.b64
          cat V.b64 | base64 -d > V.pem
          # ssh-keyscan -H wybxc.cc >> ~/.ssh/known_hosts
          chmod 600 V.pem
          echo "Start Scp!"
          scp -i V.pem -r -o "StrictHostKeyChecking no" ./docs/yiri-mirai wybxc@wybxc.cc:~/yiri-mirai-document/
